server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: SpringTest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
    cache:
      type: redis

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: test

  flyway:
    default-schema: test

services:
  second-service:
    url: ${SECOND_SERVICE_URL:http://localhost:8081}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [requestId: %X{requestId}] - %msg%n"