spring:
  application:
    name: SpringTest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: test

  flyway:
    default-schema: test

  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [requestId: %X{requestId}] - %msg%n"