/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package spring.ru.springtest.client.metadata;

import spring.ru.springtest.client.metadata.dto.BookMetadataCreateRequest;
import spring.ru.springtest.client.metadata.dto.BookMetadataResponse;
import spring.ru.springtest.client.metadata.dto.ErrorResponse;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-11T18:37:11.625413100+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "BookMetadata", description = "the BookMetadata API")
public interface BookMetadataApi {

    /**
     * POST /book-metadata : Create book metadata
     *
     * @param idempotencyKey  (required)
     * @param bookMetadataCreateRequest  (required)
     * @return Created (status code 201)
     *         or Validation error (status code 400)
     */
    @Operation(
        operationId = "createBookMetadata",
        summary = "Create book metadata",
        tags = { "BookMetadata" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BookMetadataResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Validation error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/book-metadata",
        produces = { "application/json" },
        consumes = "application/json"
    )
    @ResponseStatus(HttpStatus.CREATED)
    
    BookMetadataResponse createBookMetadata(
        @NotNull @Parameter(name = "Idempotency-Key", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Idempotency-Key", required = true) UUID idempotencyKey,
        @Parameter(name = "BookMetadataCreateRequest", description = "", required = true) @Valid @RequestBody BookMetadataCreateRequest bookMetadataCreateRequest
    );


    /**
     * GET /book-metadata/{bookId} : Get book metadata by book id
     *
     * @param bookId  (required)
     * @return Metadata found (status code 200)
     *         or Metadata not found (status code 404)
     */
    @Operation(
        operationId = "getBookMetadataByBookId",
        summary = "Get book metadata by book id",
        tags = { "BookMetadata" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Metadata found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BookMetadataResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Metadata not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/book-metadata/{bookId}",
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    
    BookMetadataResponse getBookMetadataByBookId(
        @Parameter(name = "bookId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("bookId") UUID bookId
    );

}
